name: Daily
description: "An AI powered daily planner"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^0.13.3  # Add HTTP package for API requests
  home_widget: ^0.6.0
  flutter_carousel_widget: ^2.2.0
  flutter_local_notifications: ^17.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # Define the assets folder to include images or other resources
  assets:
    - assets/1.gif 
    - assets/2.gif 
    - assets/3.gif 
    - assets/background.jpg  # Path to your avatar image

  # Define the fonts folder to include fonts
  fonts:
    - family: PressStart2P
      fonts:
        - asset: assets/PressStart2P-Regular.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
